---
- hosts: all
  become: true
  tasks:
    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
    - name: Minikube Starting
      become: ubuntu
      shell: |
        /usr/local/bin/minikube start --driver=docker && \
        /usr/local/bin/minikube kubectl -- get po -A
