---
- hosts: all
  become: true
  tasks:
    - name: Minikube Starting
      become: ubuntu
      shell:
        cmd: /usr/local/bin/minikube start --driver=docker
    - name: Checking Minikube
      become: ubuntu
      shell:
        cmd: /usr/local/bin/minikube kubectl -- get po -A
