---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: get external port
      become: ubuntu
      shell: kubectl get svc hello-kubernetes-twcc-say-hello -n twcc-svc -o=jsonpath='{.spec.ports[0].nodePort}' 
      register: SVC_PORT
    - name: show external port
      shell: echo "{{SVC_PORT.stdout}}"
    - name: update NGINX
      replace:
        path: /etc/nginx/sites-enabled/default
        regexp: 'try_files'
        replace: 'proxy_pass http://192.168.49.2:{{SVC_PORT.stdout}}; # try_files'
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: Read TWCC credential file
      shell: cat ~/.twcc_data/credential
      become_user: ubuntu
      register: twcc_credential_file
    - name: Checking API Key is in system
      become_user: ubuntu
      when: twcc_credential_file.stdout.find('twcc_api_key') == -1
      fail: msg="NO TWCC API Key, check document"
    - name: Use TWCC-CLI to open http
      become_user: ubuntu
      shell: twccli net vcs -s `hostname | cut -d- -f2` -cidr 0.0.0.0/0 -p 80 -fip
    - name: Service Public IP
      become_user: ubuntu
      shell: twccli ls vcs -s `hostname | cut -d- -f2` -json | jq -r '.[0].public_ip'
      register: SVC_ADDR

    - name: how entry
      become_user: ubuntu
      debug:
        msg:
          - "Please link to http://{{SVC_ADDR.stdout}}"

